[project]
name = "child-progress"
version = "0.1.0"
description = "儿童学习进度追踪网站"
requires-python = ">=3.9"
dependencies = [
    "streamlit>=1.28.0",
    "plotly>=5.17.0", 
    "pandas>=2.0.0",
]

[dependency-groups]
dev = []
